library(ggDNAvis)
library(patchwork)
library(ggplot2)
library(cowplot)


## Create sequence list
sequences <- list(
    sone_2019_f1_1 = "GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGAGGAGGAGGCGGCGGCGGAGGAGGAGGCGGCGGAGGAGGAGGCGGCGGAGGAGGAGGCGGCGGAGGAGGAGGCGGCGGAGGAGGAGGCGGCGGAGGAGGAGGCGGCGGAGGAGGAGGCGGCGGCGGCGGCGGCGGC",
    yu_luan_2021_f1_iii_5 = "GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGCAGGCGGCGGCGGCGGCGGCGGCGGCGCGGCGGTGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGCGGCGGCGGCGGCGGTGGCGGCGGCGGCGGCGGCGGCGGCGTGGAGGAGAGGGAGGTGGCGGGCGGCGGCGGCGGCATGGCGGCGGCGGCGGCGGCGGCGGTGGTGGCGGTGGTGGTGGTGGTGGCGGCAGGCGGTGGTGGTGGTGGTGGCGGTGGTGGCGGTGGCGGTGCGGTGGCGGCGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGCGGCGGTGGTGGAGGCAGGTGGTGGTGCAGGGCAGGAGGAGGTGGTGGTGGAGGAGGTGGTGGCGGAGGAGGTGCGCGGGAGGGAGGTGGCGGTGGAGGAGGTGGTGCGGCAGGGTGGCGGAGGAGGTGGCGGCGGAGGAGGCGGTGGCGGGAGGGAGGTGGCGGCGGAGGAGGTGGCGGCGGGAGGAGGCGGTGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGTGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGAGGCGGCGGCGGAGGAGGTGGCGGCGGAGGAGGCGGCGGTGGAGGAGGCGGCG",
    fitrah_2023_patient_14_allele_2 = "TTATTACTATTATTATTATTATTATTACTATTATTACTATTAATATTATTATTTAATATATTATTATCATTATTATTTATTATTATCATTATTATCATTATTTATCATTATTATTATCATTATCATTTACTATTACCATTATTATCATTATACATTAATATTATCATTATTTATTTATTATTACTATTATCATTACTATTATTATTATTTATTATTATTATTTATTTACTATTACTTACTATTTATTTATTATTTATTTACGATGATACGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATATTATATGATGATGAGATGATGATGATGATGATGATGATGATGATGATGATGATGAGGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGATGACGATGATGATGATGCGATGATGATGATGATGACGATGATGATGATGATGATGATGATGATGATGATGATGATGATGACATCACCGATTCACCGATGACGACGACGACGATGACGATGATGACGACGACGATGCTGACCACAGATTAATGACGACGACCACTAATTAATTATCAGGATTACCACCACTACCTGACCAGATTATTTGACGACCATTACCACTATTTTTAATTATGACACACCACTACCACCACTACTATTAATTAATACCACTTTTCACTACTTCACTACTACTACCACCACTAATTAATACCACCACCACCACTACATTACATGATTATCATACTATTTGTTTACATGATGACATTATTACTATTACTATTTACTTACTATTATTATGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGCGGCGGGTGCGGCGGCGGGCTGGCAGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC",
    yu_deng_2021_f1_iii_10 = "GGCGGCGGCGGCGCGGCCGGCGGCGGCGGCGCGGCGGCGGCGGCGGCGGCGGCGGCGGCAGCAACGGCAACGGCGGCCCTTCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCACGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCAACGGCGGCGGCGGCAGCAACGGCGGCGGCAGCAGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCAACGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGCGGCGGCAACGCAACGGCGGCGGCGGCAGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCAGCACGGCAGGCGGCGGCGGCGGCGGC"
)


## Set plotting parameters
line_wrapping <- rep(c(75, 60), times = 2)
spacing <- 1
margin <- 0.5
h_sep <- 6
v_sep <- 5.5
v_top <- 3
pixels_per_base <- 60

## Create plots
plots <- lapply(seq_along(sequences), function(i) {
    visualise_single_sequence(
        sequences[[i]],
        sequence_colours = sequence_colour_palettes$bright_pale,
        spacing = spacing,
        line_wrapping = line_wrapping[i],
        margin = margin,
        return = TRUE
    )
})


## Calculate resulting plot dimensions
heights <- sapply(seq_along(sequences), function(i) {
    seq_lines <- ceiling(nchar(sequences[[i]]) / line_wrapping[i])
    blank_lines <- (seq_lines - 1) * spacing
    margin_lines <- margin + max(1, margin)
    return(seq_lines + blank_lines + margin_lines)
})
widths <- c(line_wrapping[1], line_wrapping[2]) + 2*margin


## Calculate spacing needed on right
blank <- plot_spacer() + theme(plot.margin = grid::unit(c(0,0,0,0), "in"))

extra_right_space <- sum(heights[c(1,3)]) - sum(heights[c(2,4)])
total_height <- sum(heights[c(1,3)]) + v_sep + v_top
total_width <- sum(widths) + h_sep


## Create master plot
left_col <- (blank / plots[[1]] / blank / plots[[3]]) +
    plot_layout(heights = c(v_top, heights[1], v_sep, heights[3]))

right_col <- (blank / plots[[2]] / blank / plots[[4]]) +
    plot_layout(heights = c(v_top, heights[2], extra_right_space + v_sep, heights[4]))

main_plot <- (left_col | blank | right_col) +
    plot_layout(widths = c(widths[1], h_sep, widths[2]))


## Add annotations
text_data <- data.frame(
    x = rep(c(
        margin, 
        widths[1] + h_sep + 0.1
    ), times = 2) / total_width,
    
    y = 1 - (c(
        v_top, 
        v_top, 
        v_top + heights[1] + v_sep, 
        v_top + heights[2] + v_sep + extra_right_space - 0.25
    ) - 0.5) / total_height,
    
    label = c(
        "(a) Sone et al. (2019) F1-1", 
        "(b) Yu, Luan et al. (2021) F1-III-5", 
        "(c) Fitrah et al. (2023) Patient 14 Allele 2", 
        "(d) Yu, Deng et al. (2021) F1-III-10"
    )
)

annotated_plot <- ggdraw(main_plot) +
    geom_text(data = text_data, aes(x = x, y = y, label = label), size = 50, col = "black", hjust = 0, vjust = 0, family = "Helvetica Light", fontface = "plain") +
    theme_void()


## Export
ggsave(plot = annotated_plot, "single_sequence_notch2nlc.png", dpi = pixels_per_base, width = total_width, height = total_height, limitsize = FALSE, device = ragg::agg_png) 

